name: silk-paper
version: ${version}
main: net.silkmc.silk.paper.internal.SilkPaperEntrypoint
description: ${description}
api-version: '${mcVersion}'
# bootstrapper: io.papermc.testplugin.TestPluginBootstrap
loader: net.silkmc.silk.paper.internal.SilkPaperLoader
load: STARTUP
